export const SET_QUERY_DATA = "SET_QUERY_DATA";
export const COMPOSER_SET_REQUEST_HEADER = "COMPOSER_SET_REQUEST_HEADER";
export const COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE =
  "COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE";
